TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Models/Timesheet.cs
// ***********************************************************************
// Assembly         : TimesheetLaikas
// Author           : Donatas & Matt
// Created          : 11-30-2020
//
// Last Modified By : Donatas & Matt
// Last Modified On : 12-07-2020
// ***********************************************************************
// <copyright file="Timesheet.cs" company="TimesheetLaikas">
//     Copyright (c) HP Inc.. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TimesheetLaikas.Models
{
    /// <summary>
    /// Class Timesheet.
    /// Implements the <see cref="TimesheetLaikas.Models.EntityBase" />
    /// </summary>
    /// <seealso cref="TimesheetLaikas.Models.EntityBase" />
    [Table("Timesheet", Schema = "Pay")]
    public class Timesheet : EntityBase
    {
        //public DateTime CurrentDate { get; set; }

        /// <summary>
        /// Gets or sets the punch in.
        /// </summary>
        /// <value>The punch in.</value>
        [DisplayName("Punch In")]
        public DateTime PunchIn { get; set; }

        /// <summary>
        /// Gets or sets the punch out.
        /// </summary>
        /// <value>The punch out.</value>
        [DisplayName("Punch Out")]
        public DateTime? PunchOut { get; set; }


        /// <summary>
        /// Gets or sets the emp identifier.
        /// </summary>
        /// <value>The emp identifier.</value>
        public string EmpID { get; set; }

        /// <summary>
        /// Gets or sets the employee.
        /// </summary>
        /// <value>The employee.</value>
        [ForeignKey(nameof(EmpID))]
        public Employee Employee { get; set; }
        /// <summary>
        /// Gets or sets the statuses.
        /// </summary>
        /// <value>The statuses.</value>
        [NotMapped]
        public List<SelectListItem> Statuses { get; set; }
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        [DisplayName("Status")]
        public StatusTypes Status { get; set; }

        /// <summary>
        /// Gets or sets the total work time.
        /// </summary>
        /// <value>The total work time.</value>
        [DisplayName("Total Hours Worked")]
        public string TotalWorkTime { get; set; }

        /// <summary>
        /// Gets or sets the total pay.
        /// </summary>
        /// <value>The total pay.</value>
        [DisplayName("Total Pay")]
        public decimal? TotalPay { get; set; }
    }

    /// <summary>
    /// Enum StatusTypes
    /// </summary>
    public enum StatusTypes
    {

        /// <summary>
        /// The pending
        /// </summary>
        [Description("Pending")]
        Pending,
        /// <summary>
        /// The approved
        /// </summary>
        [Description("Approved")]
        Approved,
        /// <summary>
        /// The rejected
        /// </summary>
        [Description("Rejected")]
        Rejected
    }
}

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Models/ViewModels/TimesheetViewModel.cs
// ***********************************************************************
// Assembly         : TimesheetLaikas
// Author           : Donatas & Matt
// Created          : 11-30-2020
//
// Last Modified By : Donatas & Matt
// Last Modified On : 12-07-2020
// ***********************************************************************
// <copyright file="TimesheetViewModel.cs" company="TimesheetLaikas">
//     Copyright (c) HP Inc.. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TimesheetLaikas.Models.ViewModels
{
    /// <summary>
    /// Class TimesheetViewModel.
    /// </summary>
    public class TimesheetViewModel
    {
        /// <summary>
        /// Gets or sets the emp identifier.
        /// </summary>
        /// <value>The emp identifier.</value>
        public string EmpID { get; set; }

        /// <summary>
        /// Gets or sets the employee.
        /// </summary>
        /// <value>The employee.</value>
        [ForeignKey(nameof(EmpID))]
        public Employee Employee { get; set; }

        /// <summary>
        /// Gets or sets the punch in.
        /// </summary>
        /// <value>The punch in.</value>
        public DateTime PunchIn { get; set; }
        /// <summary>
        /// Gets or sets the punch out.
        /// </summary>
        /// <value>The punch out.</value>
        public DateTime? PunchOut { get; set; }
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        public StatusTypes Status { get; set; }
        /// <summary>
        /// Gets or sets the total work time.
        /// </summary>
        /// <value>The total work time.</value>
        public string TotalWorkTime { get; set; }
        /// <summary>
        /// Gets or sets the statuses.
        /// </summary>
        /// <value>The statuses.</value>
        [NotMapped]
        public List<SelectListItem> Statuses { get; set; }
        /// <summary>
        /// Gets or sets the total pay.
        /// </summary>
        /// <value>The total pay.</value>
        public decimal? TotalPay { get; set; }
    }
}

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Controllers/TimesheetsController.cs
// ***********************************************************************
// Assembly         : TimesheetLaikas
// Author           : Donatas & Matt
// Created          : 12-07-2020
//
// Last Modified By : Donatas & Matt
// Last Modified On : 12-07-2020
// ***********************************************************************
// <copyright file="TimesheetsController.cs" company="TimesheetLaikas">
//     Copyright (c) HP Inc.. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimesheetLaikas.Data;
using TimesheetLaikas.Models;
using TimesheetLaikas.Models.ViewModels;

namespace TimesheetLaikas.Controllers
{
    /// <summary>
    /// Class TimesheetsController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class TimesheetsController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// The user manager
        /// </summary>
        private readonly UserManager<Employee> _userManager;
        /// <summary>
        /// The role manager
        /// </summary>
        private readonly RoleManager<Roles> _roleManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="TimesheetsController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <param name="userManager">The user manager.</param>
        /// <param name="roleManager">The role manager.</param>
        public TimesheetsController(ApplicationDbContext context, UserManager<Employee> userManager, RoleManager<Roles> roleManager)
        {
            _userManager = userManager;
            _context = context;
            _roleManager = roleManager;
        }


        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Timesheet.Include(t => t.Employee);
            return View(await applicationDbContext.ToListAsync());
        }

        /// <summary>
        /// Views the timesheets.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> ViewTimesheets()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);

            var timesheets = from t in _context.Timesheet
                             where t.EmpID == currentUser.Id
                             select t;

            return View(await timesheets.AsNoTracking().ToListAsync());
        }

        /// <summary>
        /// Views the department timesheets.
        /// </summary>
        /// <returns>IActionResult.</returns>
        [Authorize(Roles = "Supervisor")]
        public async Task<IActionResult> ViewDepartmentTimesheets()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);

            var timepunches = from t in _context.Timesheet.Include(t => t.Employee)
                              where currentUser.DepartmentId == t.Employee.DepartmentId
                              select t;

            return View(await timepunches.ToListAsync());
        }

        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheet
                .Include(t => t.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            return View(timesheet);
        }

        /// <summary>
        /// Times the punch.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult TimePunch()
        {

            return View();
        }

        /// <summary>
        /// Punches the in.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PunchIn(TimesheetViewModel model)
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);

            if (ModelState.IsValid)
            {
                Timesheet timesheet = new Timesheet();

                timesheet.PunchIn = DateTime.UtcNow;

                timesheet.EmpID = currentUser.Id;


                _context.Add(timesheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ViewTimesheets));
            }


            return View(model);
        }

        /// <summary>
        /// Punches the out.
        /// </summary>
        /// <param name="timesheet">The timesheet.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PunchOut(Timesheet timesheet)
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);

            if (ModelState.IsValid)
            {
                timesheet = this._context.Timesheet
                                .Where(c => c.EmpID == currentUser.Id)
                                .OrderByDescending(t => t.PunchIn)
                                .FirstOrDefault();


                timesheet.PunchOut = DateTime.UtcNow;

                _context.Update(timesheet);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(ViewTimesheets));
            }

            return View(timesheet);
        }


        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            ViewData["EmpID"] = new SelectList(_context.Employee, "Id", "FULL_NAME");
            return View();
        }

        /// <summary>
        /// Creates the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>IActionResult.</returns>
        [Authorize(Roles = "HR")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TimesheetViewModel model)
        {
            var statuses = new List<SelectListItem>();


            if (ModelState.IsValid)
            {
                Timesheet timesheet = new Timesheet();
                {
                    timesheet.PunchIn = model.PunchIn;
                    timesheet.PunchOut = model.PunchOut;
                    timesheet.EmpID = model.EmpID;
                    timesheet.Status = StatusTypes.Pending;
                }
                if (model.PunchOut != null)
                {
                    DateTime ValidPunchOut = model.PunchOut.Value;

                    var user = _context.Employee.Find(model.EmpID);

                    TimeSpan difference = ValidPunchOut - model.PunchIn;
                    timesheet.TotalWorkTime = string.Format("{0:0}:{1:00}", difference.TotalHours, difference.Minutes);
                    decimal payrate = user.Payrate;
                    timesheet.TotalPay = payrate * difference.Hours;
                }



                _context.Add(timesheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["EmpID"] = new SelectList(_context.Employee, "Id", "FULL_NAME", model.EmpID);

            return View(model);
        }


        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            TimesheetViewModel model = new TimesheetViewModel();

            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheet.FindAsync(id);

            if (id != null)
            {

                model.EmpID = timesheet.EmpID;
                model.PunchIn = timesheet.PunchIn;
                model.PunchOut = timesheet.PunchOut;
                model.TotalWorkTime = timesheet.TotalWorkTime;
                model.TotalPay = timesheet.TotalPay;

            }

            if (timesheet == null)
            {
                return NotFound();
            }
            ViewData["EmpID"] = new SelectList(_context.Employee, "Id", "FULL_NAME", model.EmpID);
            return View(timesheet);
        }


        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="timesheet">The timesheet.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PunchIn,PunchOut,Status,EmpID,TotalWorkTime,Id,TimeStamp")] TimesheetViewModel timesheet)
        {
            if (ModelState.IsValid)
            {
                var timesheetEdit = await _context.Timesheet.FindAsync(id);

                if (timesheetEdit != null)
                {

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/Create.cshtml
@model TimesheetLaikas.Models.ViewModels.TimesheetViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Timesheet</h4>
<hr />

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-action="Create">

    <table class="table table-striped">

        <thead>
            <tr>
                <th><label asp-for="Employee.FULL_NAME" class="control-label"></label></th>
                <th><label asp-for="PunchIn" class="control-label"></label></th>
                <th> <label asp-for="PunchOut" class="control-label"></label></th>

                <th> <label asp-for="TotalWorkTime" class="control-label"></label></th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>
                    <select asp-for="EmpID" class="form-control" asp-items="ViewBag.EmpID"></select>
                    <span asp-validation-for="EmpID" class="text-danger"></span>
                </td>
                <td>
                    <input asp-for="PunchIn" class="form-control" />
                    <span asp-validation-for="PunchIn" class="text-danger"></span>
                </td>

                <td>
                    <input asp-for="PunchOut" class="form-control" />
                    <span asp-validation-for="PunchOut" class="text-danger"></span>
                </td>

                <td><input asp-for="TotalWorkTime" class="form-control" disabled /></td>
            </tr>
        </tbody>
    </table>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/Delete.cshtml
@model TimesheetLaikas.Models.Timesheet

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Timesheet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PunchIn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PunchIn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PunchOut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PunchOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalWorkTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalWorkTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/Details.cshtml
@model TimesheetLaikas.Models.Timesheet

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Timesheet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PunchIn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PunchIn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PunchOut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PunchOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalWorkTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalWorkTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/Edit.cshtml
@model TimesheetLaikas.Models.Timesheet
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Edit";
}

@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<h2>Edit</h2>

<h4>Timesheet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="EmpID" class="control-label"></label>
                <input asp-for="EmpID" class="form-control" disabled>
                <span asp-validation-for="EmpID" class="text-danger"></span>
            </div>


            @if (User.IsInRole("HR"))
            {
                <div class="form-group">
                    <label asp-for="PunchIn" class="control-label"></label>
                    <input asp-for="PunchIn" class="form-control" />
                    <span asp-validation-for="PunchIn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PunchOut" class="control-label"></label>
                    <input asp-for="PunchOut" class="form-control" />
                    <span asp-validation-for="PunchOut" class="text-danger"></span>
                </div>




            }
            else
            {
                <div class="form-group">
                    <label asp-for="PunchIn" class="control-label"></label>
                    <input asp-for="PunchIn" class="form-control" disabled />
                    <span asp-validation-for="PunchIn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PunchOut" class="control-label"></label>
                    <input asp-for="PunchOut" class="form-control" disabled />
                    <span asp-validation-for="PunchOut" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalWorkTime" class="control-label"></label>
                    <input asp-for="TotalWorkTime" class="form-control" disabled />
                    <span asp-validation-for="TotalWorkTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" asp-items="@Html.GetEnumSelectList<StatusTypes>()" class="form-control"></select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/Index.cshtml
@model IEnumerable<TimesheetLaikas.Models.Timesheet>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-primary" asp-action="Create"><i class="fas fa-plus"></i>  Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.Employee)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]"> @Html.DisplayNameFor(model => model.PunchIn)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PunchOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWorkTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)

                <div class="col-lg-12">
                    <div class="button-group">
                        <form asp-action="Index" method="get">
                            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fas fa-filter"></i></button>
                            <ul class="dropdown-menu">
                                <li><a href="#" class="small" data-value="option1" tabIndex="-1"><input type="checkbox" value="Pending" name="statusString" />&nbsp;Pending</a></li>
                                <li><a href="#" class="small" data-value="option2" tabIndex="-1"><input type="checkbox" value="Approved" name="statusString" />&nbsp;Approved</a></li>
                                <li><a href="#" class="small" data-value="option3" tabIndex="-1"><input type="checkbox" value="Rejected" name="statusString" />&nbsp;Rejected</a></li>
                                <li><input type="submit" class="btn btn-primary" value="Apply filter" /></li>
                            </ul>
                        </form>
                    </div>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FULL_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PunchIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PunchOut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalWorkTime)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.TotalPay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt"></i> Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/TImePunch.cshtml
@model IEnumerable<TimesheetLaikas.Models.Timesheet>

@{
    ViewData["Title"] = "PunchIn";
}

<h2>Clock In/Out</h2>

<body onload=display_ct();>
    <h3 id='ct'></h3>

    <div style="display:flex; ">
        <div class="btn-group mr-2" role="group" aria-label="First group">
            <form asp-action="PunchIn" asp-area="/Views/Timesheets/TimePunch" asp-controller="Timesheets">
                <button class="btn btn-lg btn-success"> Clock In</button>
            </form>
        </div>
        <div class="btn-group mr-2" role="group" aria-label="Second group">
            <form asp-action="PunchOut" asp-area="/Views/Timesheets/TimePunch" asp-controller="Timesheets">
                <button class="btn btn-lg btn-danger">Clock Out</button>
            </form>
        </div>
    </div>

</body>


<script type="text/javascript">
        //Display current time on timepunch page
    function display_c(){
    /// <summary>
    /// Displays the c.
    /// </summary>
    var refresh=1000; // Refresh rate in milli seconds
    mytime=setTimeout('display_ct()',refresh)
    }

        function display_ct() {
        /// <summary>
        /// Displays the ct.
        /// </summary>
        var x = new Date()
        document.getElementById('ct').innerHTML = x;
        display_c();
         }
</script>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/ViewDepartmentTimesheets.cshtml
@model IEnumerable<TimesheetLaikas.Models.Timesheet>

@{
    ViewData["Title"] = "ViewDepartmentTimesheets";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PunchIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PunchOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWorkTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FULL_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PunchIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PunchOut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalWorkTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TimesheetLaikas/TimesheetLaikas/TimesheetLaikas/Views/Timesheets/ViewTimesheets.cshtml
@model IEnumerable<TimesheetLaikas.Models.Timesheet>

@{
    ViewData["Title"] = "ViewTimesheets";
}

<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.PunchIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PunchOut)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TotalWorkTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPay)
            </th>
            <td>
                @Html.DisplayNameFor(model => model.Status)
            </td>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.PunchIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PunchOut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalWorkTime)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.TotalPay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
    </tbody>
</table>